services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    hostname: dash-backend
    ports:
      - "[::1]:8080:8080"
    env_file: .env
    volumes:
      - data:/data
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    hostname: dash-frontend
    env_file: .env
    ports: 
      - "[::1]:5173:3000"
    depends_on: 
      - backend
volumes:
  data:
